---
name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos7, centos8]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: "x64"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Install Dependencies
        run: |
          python --version
          pip --version
          pip install ansible "molecule[docker,lint]"
      - name: Test with molecule
        env:
          MOLECULE_DISTRO: ${{ matrix.os }}
        run: |
          cd ..
          ln -sf ansible-role-proxysql daixijun.proxysql
          cd daixijun.proxysql
          molecule test
      - name: Publish role to Galaxy
        if: success()
        run: |
          ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
